version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # setting container name manually
    container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root
    #   - MONGO_INITDB_DATABASE=admin
    # Alternative to environment variables:
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      # Anonymous volume
      - /app/node_modules
    # setting container name manually
    container_name: backend
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      # binding the container with src folder
      - ./frontend/src:/app/src
    # stdin_open tells the container it requires input
    # setting container name manually
    container_name: frontend
    stdin_open: true
    # tty attaches to the terminal
    tty: open
    depends_on:
    #OPTIONAL depends on whether or not the app needs backend to run
      - backend
      
volumes:
  data:
