version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root
    #   - MONGO_INITDB_DATABASE=admin
    # Alternative to environment variables:
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      # Anonymous volume
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
volumes:
  data:
